### ISSUE TITLE
Quick test not working for me

### ISSUE THREAD

**Issue by matths** [dinther/pathbuilder#13]
Hello,

I was just trying the Quick test with OpenSCAD version 2021.01 and was quite frustrated to see nothing.
When I remove the "z" in the end of the path string I see at least a shape similar to the one in your Readme.
As I'm quite new into your library, I have no clue yet, what the problem is, but I might find out later.
I just wanted to let you know.

Cheers, Matthias

**Comment by matths** [comment]
Some higher value to $fn makes the shape look closer to your image, but the "z" to close path is still killing the whole shape.

**Comment by dinther** [comment]
Thanks matths, I look into it. although the code has been around for a while, Not many people use it so it hasn't been shaken out that well.

**Comment by dinther** [comment]
Thanks for the report matths, I can solidify pathbuilder thanks to reports like these. Polygons imply that the path is closed. So older versions of pathbuilder simply ignored the svg "z" or "Z" command because svgShape generates a polygon and it is implied that they are closed.

So strictly speaking the demo path string with the "z" at the end was incorrect.

However, svgPoints returns a list of points and there the "Z" command is relevant so I implemented it recently. This exposed bugs in chamfer and fillet. I fixed those and solidified the code in various places.

Just pull the lastest pathbuilder.scad from the repository. I am not yet making a release. More testing to do.

**Comment by dinther** [comment]
Thanks for the report matths, I can solidify pathbuilder thanks to reports like these. Polygons imply that the path is closed. So older versions of pathbuilder simply ignored the svg "z" or "Z" command because svgShape generates a polygon and it is implied that they are closed.

So strictly speaking the demo path string with the "z" at the end was incorrect.

However, svgPoints returns a list of points and there the "Z" command is relevant so I implemented it recently. This exposed bugs in chamfer and fillet. I fixed those and solidified the code in various places.

Just pull the lastest pathbuilder.scad from the repository. I am not yet making a release. More testing to do.
